#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: http://www.xiaobo.life
#          predicates:
#            - Query=url,xiaobo